---
deployment:
      tasks:
        - composer install
        - cd /home/yanwardo/igoniometer.my.id && php artisan db:wipe
        - cd /home/yanwardo/igoniometer.my.id && php artisan migrate
        - cd /home/yanwardo/igoniometer.my.id && php artisan db:seed
