---
deployment:
      tasks:
        - export DEPLOYPATH=/home/yanwardo/igoniometer.my.id
        - cd $DEPLOYPATH
        - php artisan migrate:fresh
        - php artisan db:seed
        - mkdir storage/app/avatar
        - php artisan storage:link
 