---
deployment:
      tasks:
        - export DEPLOYPATH=/home/yanwardo/igoniometer.my.id
        - cd $DEPLOYPATH
        - php artisan db:wipe
        - php artisan migrate
        - php artisan db:seed 
        - php artisan storage:link
